# Generated by Django 4.2.27 on 2025-12-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
