# Generated by Django 4.2.27 on 2025-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_bathroom_count_alter_listing_city_lat_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='listing.listing'),
        ),
    ]
