# Generated by Django 4.2.27 on 2025-12-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
