# Generated by Django 4.2.27 on 2025-12-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_end_date_reservation_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='totalPrice',
            new_name='total_price',
        ),
    ]
