# Generated by Django 4.2.27 on 2025-12-24 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.JSONField(default=list)),
                ('country_label', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('country_flag', models.CharField(max_length=10)),
                ('country_region', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_lat', models.FloatField(blank=True, null=True)),
                ('city_lng', models.FloatField(blank=True, null=True)),
                ('guest_count', models.IntegerField()),
                ('room_count', models.IntegerField()),
                ('bathroom_count', models.IntegerField()),
                ('images', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
