# Generated by Django 4.2.27 on 2025-12-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='lat',
            new_name='country_lat',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='lng',
            new_name='country_lng',
        ),
    ]
