# Generated by Django 4.2.27 on 2025-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_rename_lat_listing_country_lat_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner', '-created_at'], name='listing_lis_owner_i_4b8a60_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['country_code', 'city_name'], name='listing_lis_country_031fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listing_lis_price_11ce52_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listing_lis_created_0f9fee_idx'),
        ),
    ]
