# Generated by Django 4.2.27 on 2025-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_bathroom_count_alter_listing_city_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='listings', to='listing.category'),
        ),
    ]
