# Generated by Django 4.2.27 on 2025-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_category_remove_listing_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
